#' @title Find the index of the latest game so far in this Premier League season
#'
#' @description This function finds the index of the most recently played game in this Premier League season.
#' @param results These are the results generated by running `get_results`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' calc_game_latest(
#'   results = data_results
#'   )
#' }
#'
#' @importFrom rlang .data

calc_game_latest <- function(results){

  results |>
    dplyr::filter(.data$played) |>
    dplyr::arrange(dplyr::desc(.data$row_order)) |>
    dplyr::slice(1) |>
    dplyr::select(.data$matchday, .data$FTHG, .data$FTAG, .data$match, .data$row_order) |>
    dplyr::pull(.data$row_order)

  }
