#' @title Calculate the points expected to be gained by each team across this Premier League season
#'
#' @description This function projects the points expected to be gained by each team across this Premier League season.
#' @param table_current This is the current table, as generated by running `calc_table_current`.
#' @param points_expected These are the expected points per team across the rest of the season, as generated by running `calc_points_expected_remaining`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' calc_points_expected_total(
#'   table_current = data_table_current,
#'   points_expected = data_points_expected_remaining
#'   )
#' }
#'
#' @importFrom rlang .data

calc_points_expected_total <- function(table_current, points_expected){

  teams <- PremPredict::teams

  projections <- table_current |>
    dplyr::arrange(.data$Team) |>
    dplyr::left_join(points_expected, by = c("Team" = "team")) |>
    dplyr::mutate(
      points_exp = .data$Points + .data$value,
      games_exp = .data$Played + .data$games_left
    ) |>
    dplyr::arrange(dplyr::desc(.data$points_exp), dplyr::desc(.data$GD)) |>
    dplyr::select("Team", "Played" = "games_exp", "Exp_Points" = "points_exp")

  projections |>
    dplyr::summarise(
      Exp_Points_Ave = mean(.data$Exp_Points),
      .by = "Team"
    ) |>
    dplyr::arrange(dplyr::desc(.data$Exp_Points_Ave)) |>
    dplyr::left_join(
      teams,
      by = c("Team" = "shortName")
    ) |>
    dplyr::select("midName", "Exp_Points_Ave")

  }
