#' @title Calculate the points expected to be gained by each team in the remainder of this Premier League season
#'
#' @description This function calculates the points expected to be gained by each team in the remainder of this Premier League season.
#' @param games_remaining These are the remaining games, with their associated model parameters, as generated by running `model_parameters_unplayed`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' calc_points_expected_remaining(
#'   games_remaining = data_results
#'   )
#' }
#'
#' @importFrom rlang .data

calc_points_expected_remaining <- function(games_remaining){

  points_home <- games_remaining |>
    dplyr::summarise(
      points = sum(.data$exp_home),
      games = dplyr::n(),
      .by = .data$team_home
    ) |>
    dplyr::select("team" = .data$team_home, .data$games, .data$points)

  points_away <- games_remaining |>
    dplyr::summarise(
      points = sum(.data$exp_away),
      games = dplyr::n(),
      .by = .data$team_away
    ) |>
    dplyr::select("team" = .data$team_away, .data$games, .data$points)

  dplyr::bind_rows(points_home, points_away) |>
    dplyr::summarise(
      value = sum(.data$points),
      games_left = sum(.data$games),
      .by = .data$team
    ) |>
    dplyr::arrange(dplyr::desc(.data$value), .data$team)

  }
