#' @title Calculate the current table for this Premier League season
#'
#' @description This function generates the latest standings of this Premier League season.
#' @param results These are the results generated by running `get_results_filtered`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' calc_table_current(
#'   results = data_results
#'   )
#' }
#'
#' @importFrom rlang .data

calc_table_current <- function(results){

  data_tabulated <- results |>
    dplyr::filter(.data$played) |>
    dplyr::mutate(
      points_home = dplyr::case_when(
        .data$FTHG > .data$FTAG ~ 3L,
        .data$FTHG == .data$FTAG ~ 1L,
        .data$FTHG < .data$FTAG ~ 0L,
        .default = NA_integer_
      ),
      points_away = dplyr::case_when(
        .data$FTHG > .data$FTAG ~ 0L,
        .data$FTHG == .data$FTAG ~ 1L,
        .data$FTHG < .data$FTAG ~ 3L,
        .default = NA_integer_
      ),
      goaldiff_home = .data$FTHG - .data$FTAG,
      goaldiff_away = .data$goaldiff_home * -1
    )

  data_table_now <- dplyr::bind_rows(
    data_tabulated |>
      dplyr::select("team" = .data$homeTeam, "points" = .data$points_home, "goaldiff" = .data$goaldiff_home),
    data_tabulated |>
      dplyr::select("team" = .data$awayTeam, "points" = .data$points_away, "goaldiff" = .data$goaldiff_away)
  ) |>
    dplyr::summarise(
      points_total = sum(.data$points),
      goaldiff_total = sum(.data$goaldiff),
      games_total = dplyr::n(),
      .by = .data$team
    ) |>
    dplyr::select("Team" = .data$team, "Played" = .data$games_total, "GD" = .data$goaldiff_total, "Points" = .data$points_total)


  }
