#' @title Calculate the result of one match, given model parameters and a uniform random variate.
#'
#' @description This function takes the relevant outcome probabilities for a match and calculates its projected result based upon the outcome of a random number generator.
#' @param data_model_parameters_unplayed_slim These are the model parameters assigned to unplayed matches in this Premier League season, as generated by `model_parameters_unplayed`, with appropriate columns retained.
#' @param randoms This is a vector of uniformly-distributed random numbers, with a length of the product of the number of remaining matches and the number of simulations.
#' @param number_sims This is the number of simulations to use for each game in the remaining season. Defaults to 50,000.
#' @param value_match This is the simulated match to choose within the `randoms` vector of many simulated matches.
#' @keywords Sport
#' @examples
#' \dontrun{
#' calc_points_simulated_match(
#'   data_model_parameters_unplayed_slim = data_model_parameters_unplayed,
#'   randoms = data_randoms,
#'   number_sims = value_number_sims,
#'   value_match = 1L
#'   )
#' }
#'
#' @importFrom rlang .data

calc_points_simulated_match <- function(data_model_parameters_unplayed_slim, randoms, number_sims, value_match){

  cutoff_draw <- data_model_parameters_unplayed_slim$prob_home[value_match]
  cutoff_lose <- data_model_parameters_unplayed_slim$prob_home[value_match] + data_model_parameters_unplayed_slim$prob_draw[value_match]
  id_match <- data_model_parameters_unplayed_slim$match[value_match]
  value_team_home <- data_model_parameters_unplayed_slim$team_home[value_match]
  value_team_away <- data_model_parameters_unplayed_slim$team_away[value_match]

  randoms_start <- (value_match - 1) * number_sims

  randoms_subset <- tibble::tibble(
    value_random = randoms[(randoms_start + 1):(randoms_start + number_sims)]
    ) |>
    tibble::rowid_to_column(var = "sim")

  randoms_subset |>
    dplyr::mutate(
      result_home = .data$value_random <= cutoff_draw,
      result_draw = (.data$value_random > cutoff_draw) & (.data$value_random <= cutoff_lose),
      points_home = (3 * .data$result_home) + .data$result_draw,
      points_away = (3 * (!.data$result_home & !.data$result_draw)) + .data$result_draw,
      match = id_match
      ) |>
    dplyr::select(-"result_home", -"result_draw")

  }
