#' @title Calculate the result of one match, given model parameters and a uniform random variate.
#'
#' @description This function takes the relevant outcome probabilities for a match and calculates its projected result based upon the outcome of a random number generator.
#' @param data_model_parameters_unplayed_slim These are the model parameters assigned to unplayed matches in this Premier League season, as generated by `model_parameters_unplayed`, with appropriate columns retained.
#' @param randoms This is a vector of uniformly-distributed random numbers, with columns called `sim` (the id variable for the simulation) and `value_random` (the random variate in each case).
#' @param value_match This is the simulated match to choose within the `randoms` vector of many simulated matches.
#' @keywords Sport
#' @examples
#' \dontrun{
#' calc_points_simulated_match(
#'   data_model_parameters_unplayed_slim = data_model_parameters_unplayed,
#'   randoms = data_randoms,
#'   value_match = 1L
#'   )
#' }
#'
#' @importFrom rlang .data

calc_points_simulated_match <- function(data_model_parameters_unplayed_slim, randoms, value_match){

  cutoff_draw <- data_model_parameters_unplayed_slim$prob_home[value_match]
  cutoff_lose <- data_model_parameters_unplayed_slim$prob_home[value_match] + data_model_parameters_unplayed_slim$prob_draw[value_match]
  id_match <- data_model_parameters_unplayed_slim$match[value_match]
  value_team_home <- data_model_parameters_unplayed_slim$team_home[value_match]
  value_team_away <- data_model_parameters_unplayed_slim$team_away[value_match]

  randoms |>
    dplyr::mutate(
      result_home = .data$value_random <= cutoff_draw,
      result_draw = (.data$value_random > cutoff_draw) & (.data$value_random <= cutoff_lose),
      points_home = (3 * .data$result_home) + .data$result_draw,
      points_away = (3 * (!.data$result_home & !.data$result_draw)) + .data$result_draw,
      match = id_match
      ) |>
    dplyr::select(-"result_home", -"result_draw")

  }
