#' @title Prepare the modelframe in order to run the prediction model
#'
#' @description This function takes the relevant filtered results from the Premier League and combines it in a way that the R prediction model can recognise.
#' @param results These are the results from this and possibly earlier seasons, as generated by `get_results_filtered`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' model_prepare_frame(
#'   results = data_results
#'   )
#' }
#'
#' @importFrom rlang .data

model_prepare_frame <- function(results){

  teams <- PremPredict::teams
  nTeams <- nrow(teams)
  teamNames <- teams$shortName

  modelframe <- gnm::expandCategorical(results, "FTR", idvar = "match") |>
    dplyr::mutate(
      draw = as.numeric(.data$FTR == "D"),
      count = dplyr::if_else((is.na(.data$FTHG) | is.na(.data$FTAG)), NA, .data$count)
    ) |>
    dplyr::select(dplyr::everything(), .data$count, .data$draw) |>
    dplyr::mutate(match = forcats::as_factor(.data$match))

  X <- matrix(0, nrow(modelframe), 2 * nTeams)
  colnames(X) <- paste0(teamNames, c(rep("_home", nTeams), rep("_away", nTeams)))

  for (team in teamNames) {
    X[modelframe$homeTeam == team & modelframe$FTR == "H", paste0(team, "_home")] <- 1
    X[modelframe$homeTeam == team & modelframe$FTR == "D", paste0(team, "_home")] <- 1/3
    X[modelframe$awayTeam == team & modelframe$FTR == "A", paste0(team, "_away")] <- 1
    X[modelframe$awayTeam == team & modelframe$FTR == "D", paste0(team, "_away")] <- 1/3
  }

  modelframe |>
    dplyr::mutate(s = X) |>
    dplyr::select(.data$match, .data$count, .data$draw, .data$s)

  }
