#' @title Assign the model parameters for unplayed games in this Premier League season.
#'
#' @description This function takes the relevant parameters from the model and assigns them to the approapriate teams in each remaining game of the season.
#' @param results These are the results from this and possibly earlier seasons, as generated by `get_results_filtered`.
#' @param model_parameters This is the output generated by `model_extract_parameters`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' model_parameters_unplayed(
#'   model_parameters = data_model_parameters,
#'   results = data_results
#'   )
#' }
#'
#' @importFrom rlang .data

model_parameters_unplayed <- function(results, model_parameters){

  results |>
    dplyr::filter(
      is.na(.data$FTHG),
      is.na(.data$FTAG)
    ) |>
    dplyr::select(.data$match, .data$homeTeam, .data$awayTeam) |>
    dplyr::left_join(model_parameters |> dplyr::filter(.data$location == "home"), c("homeTeam" = "team")) |>
    dplyr::left_join(model_parameters |> dplyr::filter(.data$location == "away"), c("awayTeam" = "team")) |>
    dplyr::select(.data$match, "team_home" = .data$homeTeam, "team_away" = .data$awayTeam, "param_home" = .data$estimate_e.x, "param_away" = .data$estimate_e.y) |>
    dplyr::rowwise() |>
    dplyr::mutate(
      value_denom = .data$param_home + .data$param_away + ((.data$param_home * .data$param_away) ^ (1/3)),
      prob_home = .data$param_home / .data$value_denom,
      prob_away = .data$param_away / .data$value_denom,
      prob_draw = ((.data$param_home * .data$param_away) ^ (1/3)) / .data$value_denom,
      exp_home = (3 * .data$prob_home) + .data$prob_draw,
      exp_away = (3 * .data$prob_away) + .data$prob_draw
    ) |>
    dplyr::ungroup()

  }
