#' @title Run the prediction model
#'
#' @description This function takes the relevant results generated in modelling the strength of the Premier League teams and extracts the relevant parameters.
#' @param model_output This is the output generated by `model_run`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' model_extract_parameters(
#'   model_output = data_model_output
#'   )
#' }
#'
#' @importFrom rlang .data

model_extract_parameters <- function(model_output){

  names(model_output$coefficients) <- c(colnames(model_output$model$s), "draw")

  outputs <- summary(model_output)

  details <- outputs$coefficients |>
    as.data.frame() |>
    tibble::rownames_to_column("team_location") |>
    dplyr::select("team_location", "estimate" = "Estimate") |>
    dplyr::rowwise() |>
    dplyr::mutate(
      estimate_e = exp(.data$estimate),
      homeTeam = dplyr::if_else(stringr::str_ends(.data$team_location, "_home"), stringr::str_sub(.data$team_location, 1, 3), NA_character_),
      awayTeam = dplyr::if_else(stringr::str_ends(.data$team_location, "_away"), stringr::str_sub(.data$team_location, 1, 3), NA_character_)
    ) |>
    dplyr::ungroup()

  dplyr::bind_rows(
    details |>
      dplyr::select("team" = "homeTeam", "estimate_e") |>
      dplyr::mutate(location = "home"),
    details |>
      dplyr::select("team" = "awayTeam", "estimate_e") |>
      dplyr::mutate(location = "away")
  ) |>
    dplyr::filter(!is.na(.data$team)) |>
    dplyr::select("team", "location", "estimate_e") |>
    dplyr::arrange(.data$team, dplyr::desc(.data$location))

  }
