#' @title Print the current table for this Premier League season
#'
#' @description This function prints the latest standings of this Premier League season.
#' @param table_latest These are the latest standings generated by running `calc_table_current`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' print_table_current(
#'   table_latest = data_calc_table_current
#'   )
#' }
#'
#' @importFrom rlang .data

print_table_current <- function(table_latest){

  table_latest |>
    dplyr::arrange(dplyr::desc(.data$Points), dplyr::desc(.data$GD)) |>
    knitr::kable()

  }
