#' @title Assign the model parameters for unplayed games in this Premier League season.
#'
#' @description This function takes the relevant parameters from the model and assigns them to the approapriate teams in each remaining game of the season.
#' @param results_thisSeason These are the results generated by running `get_openData` on the current season, such as at 'https://raw.githubusercontent.com/openfootball/football.json/refs/heads/master/2024-25/en.1.json'.
#' @param number_seasons This is the integer required for the number of previous seasons to include. It defaults to zero.
#' @param lookback_rounds This is the number of rounds of fixtures to use in a model (so 38 would represent a whole season).
#' @param number_simulations This is the number of simulations to use for each game in the remaining season. Defaults to 50,000.
#' @param value_seed This is the seed to use for the random numbers in the simulation. Defaults to 120519 (which, IMHO, was a great footballing day).
#' @keywords Sport
#' @export
#' @examples
#' run_simulations(
#'   results_thisSeason = example_thisSeason,
#'   number_seasons = 1L,
#'   lookback_rounds = 78L,
#'   number_simulations = 25000L,
#'   value_seed = 120519L
#'   )

run_simulations <- function(results_thisSeason, number_seasons, lookback_rounds, number_simulations, value_seed){

  utils::data("example_thisSeason")

  results_combined <- get_results(
    results_thisSeason = results_thisSeason,
    seasons = number_seasons
  )

  game_latest <- calc_game_latest(results = results_combined)

  results_filtered <- get_results_filtered(
    results = results_combined,
    index_game_latest = game_latest,
    lookback_rounds = lookback_rounds
  )

  data_table_current <- results_thisSeason |>
    calc_table_current()

  results_filtered |>
    model_prepare_frame() |>
    model_run() |>
    model_extract_parameters() |>
    model_parameters_unplayed(
      results = results_filtered
    ) |>
    simulate_games(
      value_number_sims = number_simulations,
      value_seed = value_seed
    ) |>
    simulate_standings(
      data_table_latest = data_table_current
    ) |>
    simulate_outcomes(
      value_number_sims = number_simulations
    )

  }
