#' @title Assign the model parameters for unplayed games in this Premier League season.
#'
#' @description This function takes the relevant parameters from the model and assigns them to the approapriate teams in each remaining game of the season.
#' @param results_thisSeason These are the results generated by running `get_openData` on the current season, such as at 'https://raw.githubusercontent.com/openfootball/football.json/refs/heads/master/2024-25/en.1.json'. The data should have the following columns and names:
#' \describe{
#'   \item{number_match}{The id values of the matches in the dataset as a character, typically from "001"}
#'   \item{number_match_integer}{the integer equivalent of the characters in `number_match`}
#'   \item{matchday}{The date of the match in yyyy-mm-dd format}
#'   \item{homeTeam}{The `shortName` of the home team, consistent with the data in the `teams` table}
#'   \item{awayTeam}{The `shortName` of the away team, consistent with the data in the `teams` table}
#'   \item{FTHG}{The integer number of goals scored in the whole match by the home team}
#'   \item{FTAG}{The integer number of goals scored in the whole match by the away team}
#'   \item{FTR}{The result of the match, as a factor of three levels ... where 'H', 'D' and 'A' represent a home win, a draw and an away win, respectively}
#'   \item{played}{A logical to show if the game has yet been played}
#'   \item{year_end}{The four figure integer value of the year in which the season ends}
#'   }
#' @param number_seasons This is the integer required for the number of previous seasons to include. It defaults to zero.
#' @param lookback_rounds This is the integer number of rounds of fixtures to use in a model (so 38L would represent a whole season). Defaults to half a season (that is, 19L).
#' @param number_simulations This is the integer number of simulations to use for each game in the remaining season. Defaults to 25000L.
#' @param value_seed This is the integer seed to use for the random numbers in the simulation. Defaults to 120519L (which, IMHO, was a great footballing day).
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' run_simulations(
#'   results_thisSeason = example_thisSeason,
#'   number_seasons = 1L,
#'   lookback_rounds = 78L,
#'   number_simulations = 25000L,
#'   value_seed = 120519L
#'   )
#'   }
#'

run_simulations <- function(results_thisSeason, number_seasons = 0L, lookback_rounds = 19L, number_simulations = 25000L, value_seed = 120519L){

  # Error checks ----

  teams <- PremPredict::teams

  if (ncol(results_thisSeason) != 10) {
    cli::cli_abort(
      c(
        "{.var results_thisSeason} has the wrong number of columns:",
        "i" = "There {?is/are} {ncol(results_thisSeason)} column{?s}.",
        "x" = "There should be 10 columns."
      )
    )
  }

  if(!(
    all(
      colnames(results_thisSeason) %in%
      c("number_match", "number_match_integer", "matchday", "homeTeam", "awayTeam", "FTHG", "FTAG", "FTR", "played", "year_end")
    )
  )){
    cli::cli_abort("Column names of {.arg results_thisSeason} can only be called 'number_match', 'number_match_integer', 'matchday', 'homeTeam', 'awayTeam', 'FTHG', 'FTAG', 'FTR', 'played' and 'year_end'.")
  }

  if(!is.data.frame(results_thisSeason)){
    cli::cli_abort("{.arg results_thisSeason} can only be used if it is a dataframe.")
  }

  if(!is.character(results_thisSeason$number_match)){
    cli::cli_abort(c(
      "{.var number_match} in {.var results_thisSeason} must be an character",
      "x" = "You've supplied a {.cls {class(results_thisSeason$number_match)}}."
    ))
  }

  if(!is.integer(results_thisSeason$number_match_integer)){
    cli::cli_abort(c(
      "{.var number_match_integer} in {.var results_thisSeason} must be an integer",
      "x" = "You've supplied a {.cls {class(results_thisSeason$number_match_integer)}}."
    ))
  }

  if(!lubridate::is.Date(results_thisSeason$matchday)){
    cli::cli_abort(c(
      "{.var matchday} in {.var results_thisSeason} must be a date",
      "x" = "You've supplied a {.cls {class(results_thisSeason$matchday)}}."
    ))
  }

  if(!(all(results_thisSeason$homeTeam %in% teams$shortName))){
    cli::cli_abort("All values of {.var homeTeam} in {.var results_thisSeason} must be a {.var shortName} in the `teams` dataset in this package.")
  }

  if(!(all(results_thisSeason$awayTeam %in% teams$shortName))){
    cli::cli_abort("All values of {.var awayTeam} in {.var results_thisSeason} must be a {.var shortName} in the `teams` dataset in this package.")
  }

  if(!is.integer(results_thisSeason$FTHG)){
    cli::cli_abort(c(
      "{.var FTHG} in {.var results_thisSeason} must be an integer",
      "x" = "You've supplied a {.cls {class(results_thisSeason$FTHG)}}."
    ))
  }

  if(!is.integer(results_thisSeason$FTAG)){
    cli::cli_abort(c(
      "{.var FTAG} in {.var results_thisSeason} must be an integer",
      "x" = "You've supplied a {.cls {class(results_thisSeason$FTAG)}}."
    ))
  }

  if(!is.factor(results_thisSeason$FTR)){
    cli::cli_abort(c(
      "{.var FTR} in {.var results_thisSeason} must be a factor",
      "x" = "You've supplied a {.cls {class(results_thisSeason$FTR)}}."
    ))
  }

  # Add FTR error check for factor levels?

  if(!is.logical(results_thisSeason$played)){
    cli::cli_abort(c(
      "{.var played} in {.var results_thisSeason} must be a logical",
      "x" = "You've supplied a {.cls {class(results_thisSeason$played)}}."
    ))
  }

  # Add year_end error check for sensible years?

  if(!is.integer(results_thisSeason$year_end)){
    cli::cli_abort(c(
      "{.var year_end} in {.var results_thisSeason} must be an integer",
      "x" = "You've supplied a {.cls {class(results_thisSeason$year_end)}}."
    ))
  }

  if(!is.integer(number_seasons)){
    cli::cli_abort(c(
        "{.var number_seasons} must be an integer",
        "x" = "You've supplied a {.cls {class(number_seasons)}}."
        ))
  }

  if(!is.integer(lookback_rounds)){
    cli::cli_abort(c(
      "{.var lookback_rounds} must be an integer",
      "x" = "You've supplied a {.cls {class(lookback_rounds)}}."
    ))
  }

  if(!is.integer(number_simulations)){
    cli::cli_abort(c(
      "{.var number_simulations} must be an integer",
      "x" = "You've supplied a {.cls {class(number_simulations)}}."
    ))
  }

  if(!is.integer(value_seed)){
    cli::cli_abort(c(
      "{.var value_seed} must be an integer",
      "x" = "You've supplied a {.cls {class(value_seed)}}."
    ))
  }


  # Main functionality ----

  utils::data("example_thisSeason")

  results_combined <- get_results(
    results_thisSeason = results_thisSeason,
    seasons = number_seasons
  )

  game_latest <- calc_game_latest(results = results_combined)

  results_filtered <- get_results_filtered(
    results = results_combined,
    index_game_latest = game_latest,
    lookback_rounds = lookback_rounds
  )

  data_table_current <- results_thisSeason |>
    calc_table_current()

  results_filtered |>
    model_prepare_frame() |>
    model_run() |>
    model_extract_parameters() |>
    model_parameters_unplayed(
      results = results_filtered
    ) |>
    simulate_games(
      value_number_sims = number_simulations,
      value_seed = value_seed
    ) |>
    simulate_standings(
      data_table_latest = data_table_current
    ) |>
    simulate_outcomes(
      value_number_sims = number_simulations
    )

  }
