#' @title Assign the model parameters for unplayed games in this Premier League season.
#'
#' @description This function takes the relevant parameters from the model and assigns them to the approapriate teams in each remaining game of the season.
#' @param data_model_parameters_unplayed These are the model parameters assigned to unplayed games in this Premier League season, as generated by `model_parameters_unplayed`.
#' @param value_number_sims This is the number of simulations to use for each game in the remaining season. Defaults to 50,000.
#' @param value_seed This is the seed to use for the random numbers in the simulation. Defaults to 120519 (which, IMHO, was a great football day).
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' simulate_games(
#'   data_model_parameters_unplayed = data_model_parameters_unplayed,
#'   value_number_sims = 1000000,
#'   value_seed = 120519L
#'   )
#' }
#'
#' @importFrom rlang .data

simulate_games <- function(data_model_parameters_unplayed, value_number_sims = 50000, value_seed = 120519L){

  set.seed(value_seed)

  data_model_parameters_unplayed |>
    dplyr::select(.data$match, .data$team_home, .data$team_away, .data$prob_home, .data$prob_away, .data$prob_draw) |>
    tidyr::expand_grid(sim = 1:value_number_sims) |>
    dplyr::rowwise() |>
    dplyr::mutate(random = stats::runif(n = 1)) |>
    dplyr::ungroup() |>
    dplyr::mutate(
      result_home = .data$random <= .data$prob_home,
      result_draw = (.data$random > .data$prob_home) & (.data$random <= (.data$prob_home + .data$prob_draw)),
      result_away = .data$random > (.data$prob_home + .data$prob_draw),
      points_home = (3 * .data$result_home) + .data$result_draw,
      points_away = (3 * .data$result_away) + .data$result_draw
    ) |>
    dplyr::select(-"result_home", -"result_draw", -"result_away")

  }
