#' @title Show the likelihoods of all possible standings for all clubs over this Premier League season.
#'
#' @description This function takes the relevant data from the simulations and the current table to the likelihoods of all possible standings for all clubs over this Premier League season.
#' @param data_standings_simulations These are the standings for each club in each scenario run, as generated by `simulate_standings`.
#' @param value_number_sims This is the number of simulations to use for each game in the remaining season. Defaults to 50,000.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' simulate_outcomes(
#'   data_standings_simulations = data_standings_simulations,
#'   value_number_sims = 1000000
#'   )
#' }
#'
#' @importFrom rlang .data

simulate_outcomes <- function(data_standings_simulations, value_number_sims){

  data_standings_simulations |>
    dplyr::count(.data$midName, .data$ranking, name = "freq") |>
    tidyr::complete(.data$midName, .data$ranking) |>
    tidyr::replace_na(
      replace = list(
        midName = NA_character_,
        ranking = NA_integer_,
        freq = 0L
        )
      ) |>
    dplyr::mutate(likelihood = .data$freq / value_number_sims) |>
    dplyr::select(-"freq") |>
    tidyr::pivot_wider(
      id_cols = "midName",
      names_from = "ranking",
      names_prefix = "p",
      values_from = "likelihood"
      ) |>
    dplyr::mutate(
      champion = .data$p1,
      top_four = .data$p1 + .data$p2 + .data$p3 + .data$p4,
      top_five = .data$top_four + .data$p5,
      top_six = .data$top_five + .data$p6,
      top_half = .data$top_six + .data$p7 + .data$p8 + .data$p9 + .data$p10,
      relegation = .data$p18 + .data$p19 + .data$p20
    ) |>
    dplyr::select("midName", "champion", "top_four", "top_five", "top_six", "top_half", "relegation") |>
    dplyr::arrange(dplyr::desc(.data$champion), dplyr::desc(.data$top_six))

  }
