#' @title Simulate the standings over this Premier League season.
#'
#' @description This function takes the relevant data from the simulations and finds the standings for each team at the end of the season.
#' @param data_game_simulations These are the outcome scenarios of the unplayed games in this Premier League season, as generated by `simulate_games`.
#' @param data_table_latest These are the latest standings generated by running `calc_table_current`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' simulate_standings(
#'   data_game_simulations = data_game_simulations,
#'   data_table_latest = data_table_latest
#'   )
#' }
#'
#' @importFrom rlang .data

simulate_standings <- function(data_game_simulations, data_table_latest){

  teams <- PremPredict::teams

  game_sims_home <- data_game_simulations |>
    dplyr::select("sim", "team" = "team_home", "points" = "points_home")

  game_sims_away <- data_game_simulations |>
    dplyr::select("sim", "team" = "team_away", "points" = "points_away")

  game_sims <- dplyr::bind_rows(game_sims_home, game_sims_away) |>
    dplyr::summarise(
      points_total = sum(.data$points),
      .by = c("sim", "team")
    ) |>
    dplyr::left_join(
      data_table_latest,
      by = c("team" = "Team")
    ) |>
    dplyr::mutate(
      points_exp = .data$Points + .data$points_total
    ) |>
    dplyr::arrange(.data$sim, dplyr::desc(.data$points_exp), dplyr::desc(.data$GD)) |>
    dplyr::select("sim", "Team" = "team", "GD", "Exp_Points" = "points_exp") |>
    dplyr::group_by(.data$sim) |>
    dplyr::mutate(ranking = dplyr::row_number()) |>
    dplyr::ungroup() |>
    dplyr::left_join(teams, by = c("Team" = "shortName")) |>
    dplyr::select("sim", "midName", "ranking")

  }
