#' @title Simulate the standings over this Premier League season.
#'
#' @description This function takes the relevant data from the simulations and finds the standings for each team at the end of the season.
#' @param data_game_simulations These are the outcome scenarios of the unplayed games in this Premier League season, as generated by `simulate_games`.
#' @param data_table_latest These are the latest standings generated by running `calc_table_current`.
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' simulate_standings(
#'   data_game_simulations = data_game_simulations,
#'   data_table_latest = data_table_latest
#'   )
#' }
#'
#' @importFrom rlang .data

simulate_standings <- function(data_game_simulations, data_table_latest){

  teams <- PremPredict::teams

  game_sims_home <- data_game_simulations |>
    dplyr::select(.data$sim, "team" = .data$team_home, "points" = .data$points_home)

  game_sims_away <- data_game_simulations |>
    dplyr::select(.data$sim, "team" = .data$team_away, "points" = .data$points_away)

  game_sims <- dplyr::bind_rows(game_sims_home, game_sims_away) |>
    dplyr::summarise(
      points_total = sum(.data$points),
      .by = c(.data$sim, .data$team)
    ) |>
    dplyr::arrange(.data$sim, .data$team) |>
    dplyr::left_join(
      data_table_latest,
      by = c("team" = "Team")
    ) |>
    dplyr::mutate(
      points_exp = .data$Points + .data$points_total
    ) |>
    dplyr::arrange(.data$sim, dplyr::desc(.data$points_exp), dplyr::desc(.data$GD)) |>
    dplyr::select(.data$sim, "Team" = .data$team, .data$GD, "Exp_Points" = .data$points_exp) |>
    dplyr::group_by(.data$sim) |>
    dplyr::mutate(ranking = dplyr::row_number()) |>
    dplyr::ungroup() |>
    dplyr::left_join(teams, by = c("Team" = "shortName")) |>
    dplyr::select(.data$sim, .data$midName, .data$ranking)

  # teams <- PremPredict::teams
  #
  # game_sims_home <- data_game_simulations |>
  #   dplyr::select(.data$sim, .data$team_home, .data$points_home) |>
  #   dplyr::summarise(
  #     points_home_total = sum(.data$points_home),
  #     # n_home = dplyr::n(),
  #     .by = c(.data$sim, .data$team_home)
  #   )
  #
  # game_sims_away <- data_game_simulations |>
  #   dplyr::select(.data$sim, .data$team_away, .data$points_away) |>
  #   dplyr::summarise(
  #     points_away_total = sum(.data$points_away),
  #     # n_away = dplyr::n(),
  #     .by = c(.data$sim, .data$team_away)
  #   )
  #
  # game_sims_home |>
  #   dplyr::left_join(
  #     game_sims_away,
  #     by = c("sim" = "sim", "team_home" = "team_away")
  #   ) |>
  #   dplyr::arrange(.data$sim, .data$team_home) |>
  #   dplyr::rowwise() |>
  #   dplyr::mutate(
  #     points_total = .data$points_home_total + .data$points_away_total,
  #     # n_total = .data$n_home + .data$n_away
  #   ) |>
  #   dplyr::ungroup() |>
  #   dplyr::select(.data$sim, "team" = .data$team_home, .data$points_total) |>   #, .data$n_total) |>
  #   dplyr::left_join(
  #     data_table_latest,
  #     by = c("team" = "Team")
  #   ) |>
  #   dplyr::mutate(
  #     points_exp = .data$Points + .data$points_total,
  #     # games_exp = .data$Played + .data$n_total
  #   ) |>
  #   dplyr::arrange(.data$sim, dplyr::desc(.data$points_exp), dplyr::desc(.data$GD)) |>
  #   # dplyr::select(.data$sim, "Team" = .data$team, "Played" = .data$games_exp, .data$GD, "Exp_Points" = .data$points_exp) |>
  #   dplyr::select(.data$sim, "Team" = .data$team, .data$GD, "Exp_Points" = .data$points_exp) |>
  #   dplyr::group_by(.data$sim) |>
  #   dplyr::mutate(ranking = dplyr::row_number()) |>
  #   dplyr::ungroup() |>
  #   dplyr::left_join(teams, by = c("Team" = "shortName")) |>
  #   dplyr::select(.data$sim, .data$midName, .data$ranking)


  }
