#' @title Assign the model parameters for unplayed games in this Premier League season.
#'
#' @description This function takes the relevant parameters from the model and assigns them to the approapriate teams in each remaining game of the season.
#' @param data_model_parameters_unplayed These are the model parameters assigned to unplayed games in this Premier League season, as generated by `model_parameters_unplayed`.
#' @param value_number_sims This is the number of simulations to use for each game in the remaining season. Defaults to 50,000.
#' @param value_seed This is the seed to use for the random numbers in the simulation. Defaults to 120519 (which, IMHO, was a great footballing day).
#' @keywords Sport
#' @export
#' @examples
#' \dontrun{
#' simulate_games(
#'   data_model_parameters_unplayed = data_model_parameters_unplayed,
#'   value_number_sims = 1000000,
#'   value_seed = 120519L
#'   )
#' }
#'
#' @importFrom rlang .data

simulate_games <- function(data_model_parameters_unplayed, value_number_sims = 50000, value_seed = 120519L){

  number_matches <- nrow(data_model_parameters_unplayed)

  set.seed(value_seed)
  randoms_superset <- stats::runif(n = value_number_sims * number_matches)

  slim_parameters_unplayed <- data_model_parameters_unplayed |>
    dplyr::select("match", "team_home", "team_away", "prob_home", "prob_draw")

  test_now <- purrr::map(
    .x = 1:number_matches,
    .f = ~calc_points_simulated_match(
      data_model_parameters_unplayed_slim = slim_parameters_unplayed,
      randoms = randoms_superset,
      number_sims = value_number_sims,
      value_match = .x
      )
    ) |>
    dplyr::bind_rows() |>
    dplyr::left_join(
      data_model_parameters_unplayed |>
        dplyr::select("match", "team_home", "team_away"),
      by = c("match" = "match")
    )

  }
